runtime: python27
api_version: 1
threadsafe: yes
default_expiration: 1h

handlers:
- url: /
  static_files: index.html
  upload: index\.html
  secure: always

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
