application: jasoncartwrightdotcom
version: basic
runtime: python
api_version: 1
threadsafe: yes
default_expiration: 1h

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /photo.jpg
  static_files: photo.jpg
  upload: photo\.jpg

- url: /bg.png
  static_files: bg.png
  upload: bg\.png